#!/data/data/com.termux/files/usr/bin/sh

if [ "$#" -eq 1 ] && [ "$1" = "-d" ]; then
    exec /data/data/com.termux/files/usr/bin/unused/passwd "$@"
elif [ "$#" -eq 0 ]; then
    exec /data/data/com.termux/files/usr/bin/unused/passwd
else
    proot-distro login alpine -- passwd "$@"
fi
